package it.fivano.symusic.backend.model;

import java.io.Serializable;

public class PopularKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popular_key.id_popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    private Long idPopularKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popular_key.id_user
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    private Long idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popular_key.string_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    private String stringKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popular_key.count_ref
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    private Integer countRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popular_key.id_popular_key
     *
     * @return the value of popular_key.id_popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public Long getIdPopularKey() {
        return idPopularKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popular_key.id_popular_key
     *
     * @param idPopularKey the value for popular_key.id_popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setIdPopularKey(Long idPopularKey) {
        this.idPopularKey = idPopularKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popular_key.id_user
     *
     * @return the value of popular_key.id_user
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popular_key.id_user
     *
     * @param idUser the value for popular_key.id_user
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popular_key.string_key
     *
     * @return the value of popular_key.string_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public String getStringKey() {
        return stringKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popular_key.string_key
     *
     * @param stringKey the value for popular_key.string_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setStringKey(String stringKey) {
        this.stringKey = stringKey == null ? null : stringKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popular_key.count_ref
     *
     * @return the value of popular_key.count_ref
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public Integer getCountRef() {
        return countRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popular_key.count_ref
     *
     * @param countRef the value for popular_key.count_ref
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setCountRef(Integer countRef) {
        this.countRef = countRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PopularKey other = (PopularKey) that;
        return (this.getIdPopularKey() == null ? other.getIdPopularKey() == null : this.getIdPopularKey().equals(other.getIdPopularKey()))
            && (this.getIdUser() == null ? other.getIdUser() == null : this.getIdUser().equals(other.getIdUser()))
            && (this.getStringKey() == null ? other.getStringKey() == null : this.getStringKey().equals(other.getStringKey()))
            && (this.getCountRef() == null ? other.getCountRef() == null : this.getCountRef().equals(other.getCountRef()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdPopularKey() == null) ? 0 : getIdPopularKey().hashCode());
        result = prime * result + ((getIdUser() == null) ? 0 : getIdUser().hashCode());
        result = prime * result + ((getStringKey() == null) ? 0 : getStringKey().hashCode());
        result = prime * result + ((getCountRef() == null) ? 0 : getCountRef().hashCode());
        return result;
    }
}