package it.fivano.symusic.backend.model;

import java.util.ArrayList;
import java.util.List;

public class PopularKeyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public PopularKeyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdPopularKeyIsNull() {
            addCriterion("id_popular_key is null");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyIsNotNull() {
            addCriterion("id_popular_key is not null");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyEqualTo(Long value) {
            addCriterion("id_popular_key =", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyNotEqualTo(Long value) {
            addCriterion("id_popular_key <>", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyGreaterThan(Long value) {
            addCriterion("id_popular_key >", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyGreaterThanOrEqualTo(Long value) {
            addCriterion("id_popular_key >=", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyLessThan(Long value) {
            addCriterion("id_popular_key <", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyLessThanOrEqualTo(Long value) {
            addCriterion("id_popular_key <=", value, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyIn(List<Long> values) {
            addCriterion("id_popular_key in", values, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyNotIn(List<Long> values) {
            addCriterion("id_popular_key not in", values, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyBetween(Long value1, Long value2) {
            addCriterion("id_popular_key between", value1, value2, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdPopularKeyNotBetween(Long value1, Long value2) {
            addCriterion("id_popular_key not between", value1, value2, "idPopularKey");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNull() {
            addCriterion("id_user is null");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNotNull() {
            addCriterion("id_user is not null");
            return (Criteria) this;
        }

        public Criteria andIdUserEqualTo(Long value) {
            addCriterion("id_user =", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotEqualTo(Long value) {
            addCriterion("id_user <>", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThan(Long value) {
            addCriterion("id_user >", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("id_user >=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThan(Long value) {
            addCriterion("id_user <", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThanOrEqualTo(Long value) {
            addCriterion("id_user <=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserIn(List<Long> values) {
            addCriterion("id_user in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotIn(List<Long> values) {
            addCriterion("id_user not in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserBetween(Long value1, Long value2) {
            addCriterion("id_user between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotBetween(Long value1, Long value2) {
            addCriterion("id_user not between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andStringKeyIsNull() {
            addCriterion("string_key is null");
            return (Criteria) this;
        }

        public Criteria andStringKeyIsNotNull() {
            addCriterion("string_key is not null");
            return (Criteria) this;
        }

        public Criteria andStringKeyEqualTo(String value) {
            addCriterion("string_key =", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyNotEqualTo(String value) {
            addCriterion("string_key <>", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyGreaterThan(String value) {
            addCriterion("string_key >", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyGreaterThanOrEqualTo(String value) {
            addCriterion("string_key >=", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyLessThan(String value) {
            addCriterion("string_key <", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyLessThanOrEqualTo(String value) {
            addCriterion("string_key <=", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyLike(String value) {
            addCriterion("string_key like", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyNotLike(String value) {
            addCriterion("string_key not like", value, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyIn(List<String> values) {
            addCriterion("string_key in", values, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyNotIn(List<String> values) {
            addCriterion("string_key not in", values, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyBetween(String value1, String value2) {
            addCriterion("string_key between", value1, value2, "stringKey");
            return (Criteria) this;
        }

        public Criteria andStringKeyNotBetween(String value1, String value2) {
            addCriterion("string_key not between", value1, value2, "stringKey");
            return (Criteria) this;
        }

        public Criteria andCountRefIsNull() {
            addCriterion("count_ref is null");
            return (Criteria) this;
        }

        public Criteria andCountRefIsNotNull() {
            addCriterion("count_ref is not null");
            return (Criteria) this;
        }

        public Criteria andCountRefEqualTo(Integer value) {
            addCriterion("count_ref =", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefNotEqualTo(Integer value) {
            addCriterion("count_ref <>", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefGreaterThan(Integer value) {
            addCriterion("count_ref >", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefGreaterThanOrEqualTo(Integer value) {
            addCriterion("count_ref >=", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefLessThan(Integer value) {
            addCriterion("count_ref <", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefLessThanOrEqualTo(Integer value) {
            addCriterion("count_ref <=", value, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefIn(List<Integer> values) {
            addCriterion("count_ref in", values, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefNotIn(List<Integer> values) {
            addCriterion("count_ref not in", values, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefBetween(Integer value1, Integer value2) {
            addCriterion("count_ref between", value1, value2, "countRef");
            return (Criteria) this;
        }

        public Criteria andCountRefNotBetween(Integer value1, Integer value2) {
            addCriterion("count_ref not between", value1, value2, "countRef");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table popular_key
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 28 11:41:27 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table popular_key
     *
     * @mbg.generated Sun Jan 28 11:41:27 CET 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}